name: BanAnnouncer
author: OopsieWoopsie
main: eu.mcdb.ban_announcer.bukkit.BanAnnouncerBukkit
version: ${project.version}
depend: [Spicord]
softdepend: [AdvancedBan, LiteBans, MaxBansPlus, Essentials, BetterJails]
loadbefore: [MaxBansPlus]
description: Announce the punishments on your Discord server
